pipeline:
  name: test-electron2
  identifier: testelectron2
  projectIdentifier: NgLabs
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: linux-make-src-cache
        identifier: linuxmakesrccache
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - stepGroup:
                  name: electron-build
                  identifier: electronbuild
                  steps:
                    - step:
                        type: Run
                        name: Install gnu-tar on macos
                        identifier: Install_gnutar_on_macos
                        spec:
                          shell: Sh
                          command: |-
                            #!/bin/bash -eo pipefail
                            if [ "`uname`" == "Darwin" ]; then
                              if [ ! -d /usr/local/Cellar/gnu-tar/ ]; then
                                brew update
                                brew install gnu-tar
                              fi
                              ln -fs /usr/local/bin/gtar /usr/local/bin/tar
                            fi
                    - step:
                        type: Run
                        name: Install python2 on mac
                        identifier: Install_python2_on_mac
                        spec:
                          shell: Sh
                          command: |
                            #!/bin/bash -eo pipefail
                            if [ "`uname`" == "Darwin" ] && [ "$IS_ELECTRON_RUNNER" != "1" ]; then
                              if [ ! -f "python-downloads/python-2.7.18-macosx10.9.pkg" ]; then
                                mkdir python-downloads
                                echo 'Downloading Python 2.7.18'
                                curl -O https://dev-cdn.electronjs.org/python/python-2.7.18-macosx10.9.pkg
                                mv python-2.7.18-macosx10.9.pkg python-downloads
                              else
                                echo 'Using Python install from cache'
                              fi
                              sudo installer -pkg python-downloads/python-2.7.18-macosx10.9.pkg -target /        
                            fi
                    - step:
                        type: SaveCacheGCS
                        name: Persisting python cache
                        identifier: Persisting_python_cache
                        spec:
                          connectorRef: gcpdhruba
                          bucket: test-electron
                          key: v2.7.18-python-cache-{{ arch }}
                          sourcePaths:
                            - python-downloads
                          archiveFormat: Tar
                  when:
                    stageStatus: All
                  failureStrategies: []
                  spec: {}
        variables:
          - name: GCLIENT_EXTRA_ARGS
            type: String
            description: ""
            value: "'--custom-var=checkout_arm=True --custom-var=checkout_arm64=True'"
  properties:
    ci:
      codebase:
        connectorRef: gitconnectordhruba
        repoName: electron
        build: <+input>
